### ISSUE TITLE
You never go full TAPS

### ISSUE THREAD

**Issue by DavidSchinazi** [martinduke/congestion-control-charter#10]
The charter currently states:
> Define a conceptual framework for describing abstract algorithms that can have concrete instantiations for each transport, and an approach to documenting each.

This sounds like quite a distraction from the useful work of new congestion control algorithms. In the real world, we have TCP and QUIC - we don't need an ontology here of all hypothetical options that will then only ever be instantiated exactly twice for QUIC and TCP.

**Comment by mwelzl** [comment]
I'm trying to understand if this is TAPS-bashing or not (if it is: I hate you  :-D  ). Also, MP-DCCP might become used, MPTCP exists, Adobe's RTMFP may still be alive... we also have GCC over UDP in WebRTC, and even SCTP in WebRTC...

But, what is this even about?  Regarding the quoted statement from the charter, I agree that this sounds like a distraction.

**Comment by DavidSchinazi** [comment]
I can neither confirm nor deny the presence of bashing of any existing WG in the previous statement :-)

My main point is that the CONGRESS WG should work on congestion control algorithms, not abstract models of what a congestion control algorithm is.

**Comment by mwelzl** [comment]
Indeed, and see issue #12: ICCRG has produced such meta-stuff in the past (and if they enjoy, they still can do more of it).  I'm not sure how useful this is, but YES, let's please have a group that specifies algorithms.

**Comment by mwelzl** [comment]
(for some reason, when I chaired ICCRG, whenever I offered "publish Experimental via ICCRG" to authors, they got scared and ran away. I believe it was the "RG" label, but I really don't know. Maybe it was me  :-D  :-D   ).   So ... there's a gap here that CONGRESS can fill.

**Comment by martinduke** [comment]
I am trying to say that these algorithms should be written to support multiple algorithms if possible, and that the group should decide on a template for that. I'm just not saying it well.
