### ISSUE TITLE
Bikeshedding the WG name

### ISSUE THREAD

**Issue by chromi** [martinduke/congestion-control-charter#18]
Instead of CONGRESS (Congestion Response & Signalling), I propose:

C-SAR (Congestion Signalling & Response).

Hopefully with less backstabbing than the original.

**Comment by martinduke** [comment]
another suggestion was CROCS (Congestion RespOnse and Congestion Signaling)

**Comment by martinduke** [comment]
Congestion Assessment and Response (CAR)

**Comment by martinduke** [comment]
Congestion Response, Assessment, Prediction, and Signaling (CRAPS)

**Comment by nealcardwell** [comment]
Internet CongEstion Control, REsponse, And Management (ICECREAM)

**Comment by bbriscoe** [comment]
> Congestion Assessment and Response (CAR)

The charter rules that Assessment is for ICCRG and out of scope here.

**Comment by zaheduzzaman** [comment]
with no hat on -

Congestion Avoidance techniques, Responses and Signalling - CARS

**Comment by mohittahiliani** [comment]
CONgestion Control and Avoidance Techniques (CONCAT)

**Comment by martinduke** [comment]
The sponsoring AD has chosen to stick with CONGRESS, closing

**Comment by ekinnear** [comment]
In the side meeting at IETF 115, there was broad support for changing the name to something less... not great, provided that a better answer was found. Seems like this issue has a bunch of better suggestions, any reason not to switch things over?

**Comment by zaheduzzaman** [comment]
Seems like there are some disquiet about the name "congress" :-) .. so in the quest of new name @martinduke we should reopen this issue again to discuss potential alternatives.

**Comment by renghardt** [comment]
Agreed. I like CROCS and ICECREAM best :slightly_smiling_face: 
Though I'm not sure what exactly "congestion management" is, a Web search mostly shows results related to transportation/driving. Can anyone define this term in a networking context for me, please?

**Comment by martinduke** [comment]
With no hats on, I suggest we just call it the Congestion working group. Being cute has not rewarded us, so let's just be descriptive instead.

**Comment by MischMetal** [comment]
In case we do call it CROCS :)
![image](https://user-images.githubusercontent.com/10251663/225979049-f13e7e43-808d-4137-b7a2-04775d8102e1.png)

**Comment by martinduke** [comment]
I would also be satisfied with 'decongest'. Again, no acronym.

**Comment by ekinnear** [comment]
In the spirit of being as simple as possible, `congestion control working group`? 

(And if we need an acronym, `ccwg`?)

**Comment by martinduke** [comment]
there was a comment a while back that "congestion control" was a bad term that we should get away from, so I didn't propose that, but I wouldn't object.

**Comment by jefftant** [comment]
+1 CROCS, against I(nternet) in the name

**Comment by MischMetal** [comment]
+1 for CROCS too!
![image](https://user-images.githubusercontent.com/10251663/226078293-b7aeb1dd-6416-4704-9414-e68e6fb37c64.png)

**Comment by renghardt** [comment]
The chairs (@ekinnear and myself) have decided to name the new WG the Congestion Control Working Group (CCWG), rather than CONGRESS.

Two main reasons:

* CCWG is clear and direct -- Trying to be cute has not served us well.
* CCWG is easy to contrast with ICCRG, which may help when explaining the difference.

We will get a new mailing list and (if I understand correctly) migrate all subscribers as well as the mailing list archive.
