### ISSUE TITLE
Empirical evidence of safety

### ISSUE THREAD

**Issue by boucadair** [martinduke/congestion-control-charter#21]
> Adoption of standards-track work should consider empirical evidence of safety and stated intent to deploy by major transport implementations.

It is true that targeted CC mechanisms in CONGRESS will be those that are generic and applicable to many transport protocols. However, assessing CC compliance for some transports may be problematic as per https://datatracker.ietf.org/doc/html/rfc9065#section-2.4.3. The question is then how/who will provide the data to assess the safety/fairness. 

We may add a sentence to say that the logistics about how such evidence is set/established will be further detailed by the WG.

**Comment by martinduke** [comment]
The implicit assumption here is that if you come with a proposal, you probably ought to come with some data as well, though I suppose third parties might also provide such data. If it's standards track there really ought to have been an experimental deployment of some kind that has data.

I don't think the WG will set up a set of standing policies for what data is required beyond what's in existing RFCs and RFC5033bis. In particular, certain proposals will require special emphasis (e.g., TCP Prague would require a close look at RFC3168 coexistence).

Do you still think we need more text here?

**Comment by boucadair** [comment]
Thanks, Martin. 

I do think there is a value in including text such as: 
 
`In order to ease the reproducibility and analysis of the data, the WG might establish a set of guidelines (e.g. data diversity, access to the data source, third party observation) and/or define a template for documenting the empirical data.`

**Comment by martinduke** [comment]
But this is part of RFC 5033 (Sec 3)! Data requirements are clearly in scope given that they're part of the document under revision.

**Comment by boucadair** [comment]
Which part of that section are you referring to?

Thanks.

**Comment by martinduke** [comment]
the entire section is test conditions that should be evaluated.

**Comment by VMatrix1900** [comment]
I do not think it is possible to enforce very concrete rules about the data evaluation in the WG. Just let the community validate the dataset case by case.

**Comment by martinduke** [comment]
Closing because this is defined in RFC5033, and thus clearly in scope.
