### ISSUE TITLE
Add FQ?

### ISSUE THREAD

**Issue by dtaht** [martinduke/congestion-control-charter#22]
Given the extent to which fair and flow queuing techniques are in the marketplace today, I don't feel a conversation about congestion control can exclude it. In particular, were flow queuing become even more ubiquitous, it opens new opportunities for paced transports and delay based congestion controls to not only just work, but work with even finer grained granularity stepping up or down. 

(I try to make a conscientious distinction nowadays between "fair queuing" where a new flow goes to the end of the flow list, and flow queuing, where a flow that has not been seen over the service time of all the other flows, goes out first) 

As one example of what can be done with a FQ aware congestion control, see: https://arxiv.org/abs/2206.10561

**Comment by martinduke** [comment]
AQMs are already included as in scope.

**Comment by dtaht** [comment]
I don't conflate FQ with AQM. How is it that you do?

**Comment by martinduke** [comment]
TBH I have always colloquially used "AQM" to refer to all types of queuing disciplines.

Sorry for the imprecision, reopening.

**Comment by dtaht** [comment]
Thx!
