### ISSUE TITLE
rmcat does appear to be nearly dead

### ISSUE THREAD

**Issue by dtaht** [martinduke/congestion-control-charter#24]
And doing any level of future congestion control work MUST include the demands of videoconferencing, the most needed app of the last few years, and still one of the most problematic.

**Comment by martinduke** [comment]
There are some problem areas that aren't specifically related to this, and until rmcat is *actually* dead, we can't take the charter any farther than this.

**Comment by martinduke** [comment]
#26 rewrites this a bit, based on the responsible AD's stated intent to close RMCAT when other document actions are complete. closing.
