### ISSUE TITLE
Congestion control on wireless transports

### ISSUE THREAD

**Issue by dtaht** [martinduke/congestion-control-charter#25]
The wireless congestion control problems remain severe, be it wifi, or 5G, and few solutions have appeared that seem to work (I'm not aware of anything sane here besides preseem/libreqos/paraqum/etc middleboxes). Most of the time the IETF seems to think about CCs as if everything were like ethernet, isochronous, and not wireless, where transports are deeply affected by bursts, retries, power save features, and so on , and the last mile, mostly wireless.

I would welcome, I guess, this group, or others, razor-sharp focused on the problems 5G and wifi bring to the congestion control issues we ahve today.

**Comment by renghardt** [comment]
I agree that congestion controllers need to take these issues into account, given the ubiquity of wireless links. However, I'm not aware of any solutions that are broadly deployed and that seem to really address these issues either.
So I'm not sure that wireless links need to be included explicitly in this charter, but we surely need to consider them as part of the general Internet.

There is a lot of interesting research about these topics, and perhaps ICCRG would be a great venue for these discussions. I also remember that a few years ago, there were several PANRG-related side meetings around ["Performance Implications of Path Characteristics"](https://datatracker.ietf.org/meeting/105/materials/slides-105-panrg-performance-implications-of-path-characteristics-01). I don't remember if there was any specific outcome of these meetings, but participants acknowledged that most of this is still research, unfortunately.

**Comment by martinduke** [comment]
I'm not sure what this issue is actually requesting. RFC5033 mentioned wireless network performance as a criterion for evaluation. It would certainly be in scope to update this text with whatever concerns @dtaht thinks are appropriate.

In my opinion, there is no need for the charter to change to address this issue.

**Comment by zaheduzzaman** [comment]
Yes, wireless and cellular access creates certain issues that need to be taken into account. The rmcat working group had worked with wireless focused CCs by making sure there is wireless testcases for that purpose. So the community seems to care about that particular access network.

I agree that RFC5033 mentions about wireless access and I also believe when we mean Internet we also mean all kind of links and path. I don't feel like we need to specifically mention particular access networks  or links as I don't see that the current charter prohibits working of CCs focused on any particular access network. 

Having said that I would be happy and encourage the working group to work on CCs considering wireless access issues by default.

**Comment by martinduke** [comment]
Sounds like there's agreement there is no need to change the charter for this; closing.
