### ISSUE TITLE
We need milestones.

### ISSUE THREAD

**Issue by zaheduzzaman** [martinduke/congestion-control-charter#30]
We need milestones for this charter.

**Comment by zaheduzzaman** [comment]
@theri and @ekinnear , tagging to let you know about it.

**Comment by martinduke** [comment]
IMO there is one milestone: 5033bis

I don't think it would be good to have the milestone in the charter text, because the milestone list will change as proposals come in, as hopefully this will be a long-lived group.

Milestone format (dates or not) is up to the chairs.

**Comment by zaheduzzaman** [comment]
We need at least one milestone to start with so that we know what we are upto. 5033bis is an obvious one. If there is no other obvious ones then lets start with that.

In a separate email discussion with chairs, I told that we don't need timed milestone for this WG. The chairs can choose the format of it as they prefer.

**Comment by zaheduzzaman** [comment]
We are not going with one milestone 5033bis
