### ISSUE TITLE
Potential congestion control algorithm scope and milestone

### ISSUE THREAD

**Issue by zaheduzzaman** [martinduke/congestion-control-charter#37]
https://github.com/martinduke/congestion-control-charter/blob/1a2c7a8b83c7cf089185a8ce49fbdb5516dea0db/congestion-control-charter.md?plain=1#L22-L29

These description still might initiate the question of missing related milestone for the topics. Hence I would suggest that we add a conditional action - 

> The working group is intended to be a home for such work, and it is chartered to adopt proposals in this space if such congestion control algorithms are presented during the completion of the initial deliverable (5033bis).

**Comment by renghardt** [comment]
This sounds good to me. See PR #38

**Comment by martinduke** [comment]
I thought we had ended up with requiring a recharter for additional work, per IESG feedback?

**Comment by ekinnear** [comment]
For additional work beyond the initial scope, but upon discussion we wanted to include the first round of that work upfront, rather than coming back immediately and surprising people

**Comment by renghardt** [comment]
Addressed this comment by merging PR #38
