### ISSUE TITLE
Past questions?

### ISSUE THREAD

**Issue by DavidSchinazi** [martinduke/congestion-control-charter#8]
The current text states `Over the last few years, several developments have raised questions about the value of this model:` followed by six bullets. First, a small nit: none of these actually contain questions. But more importantly, while points are incredibly helpful to help motivate the formation of a new WG, they don't belong in the final charter. The goal of a charter is to scope of the work of a WG, not motivate its existence.

**Comment by martinduke** [comment]
OK, I'll shorten it up

**Comment by martinduke** [comment]
Fixed by #16
